### PR TITLE
Fixed TimeSpan out of bounds errors when trying to use the Replace feature

### PR DESCRIPTION
**Pull request by MatheusMK3**

### CODE REVIEW

**Comment by pedrohugorm** [comment]
I was trying to grab your branch and build it locally but I'm getting errors for the VRage Library.

These

`  ToolboxPlatform.cs(5, 21): [CS0234] The type or namespace name 'Exceptions' does not exist in the namespace 'VRage.Library' (are you missing an assembly reference?)
  ToolboxPlatform.cs(92, 21): [CS0246] The type or namespace name 'MyDriverDetails' could not be found (are you missing a using directive or an assembly reference?)
  ToolboxPlatform.cs(147, 93): [CS0426] The type name 'ExceptionInfo' does not exist in the type 'MyMiniDump'
  ToolboxPlatform.cs(11, 36): [CS0535] 'ToolboxPlatform' does not implement interface member 'IVRagePlatform.Init()'
  ToolboxPlatform.cs(11, 36): [CS0535] 'ToolboxPlatform' does not implement interface member 'IVRagePlatform.Update()'
  ToolboxPlatform.cs(11, 36): [CS0535] 'ToolboxPlatform' does not implement interface member 'IVRagePlatform.Done()'
  ToolboxPlatform.cs(11, 36): [CS0535] 'ToolboxPlatform' does not implement interface member 'IVRagePlatform.CreateInput2()'
  ToolboxPlatform.cs(11, 36): [CS0738] 'ToolboxPlatform' does not implement interface member 'IVRagePlatform.InitAnalytics(string, string)'. 'ToolboxPlatform.InitAnalytics(string, string)' cannot implement 'IVRagePlatform.InitAnalytics(string, string)' because it does not have the matching return type of 'IMyAnalytics'.
  ToolboxPlatform.cs(11, 36): [CS0535] 'ToolboxPlatform' does not implement interface member 'IVRagePlatform.GetTypeModel()'
  ToolboxPlatform.cs(11, 36): [CS0535] 'ToolboxPlatform' does not implement interface member 'IVRagePlatform.Windows'
  ToolboxPlatform.cs(11, 36): [CS0535] 'ToolboxPlatform' does not implement interface member 'IVRagePlatform.Http'
  ToolboxPlatform.cs(11, 36): [CS0535] 'ToolboxPlatform' does not implement interface member 'IVRagePlatform.System'
  ToolboxPlatform.cs(11, 36): [CS0535] 'ToolboxPlatform' does not implement interface member 'IVRagePlatform.Render'
  ToolboxPlatform.cs(11, 36): [CS0535] 'ToolboxPlatform' does not implement interface member 'IVRagePlatform.Input2'
  ToolboxPlatform.cs(11, 36): [CS0535] 'ToolboxPlatform' does not implement interface member 'IVRagePlatform.Audio'
  ToolboxPlatform.cs(11, 36): [CS0535] 'ToolboxPlatform' does not implement interface member 'IVRagePlatform.CrashReporting'`

Any idea of what the issue is or what I might be missing?

The DLL paths are correct. Seems they just don't have the classes referenced.

I updated SE with latest version as of TODAY by the way.

**Comment by MatheusMK3** [comment]
@pedrohugorm I will have to investigate on that, there's a chance Keen might have changed the implementation on the latest updates (specially after the new DLC) and thus broken something, since SEToobox by default copies over the game's binaries instead of linking them directly (probably due to licensing)

**Comment by MatheusMK3** [comment]
Hello @pedrohugorm, which fork are you trying to build? I managed to successfully build my fork earlier today. Pulled the latest code from this (@mmusu3's repo) fork and added a release with the working binaries, in case you need them.

**Comment by mmusu3** [comment]
@MatheusMK3 Hi sorry I didn't see this earlier, I didn't get a notification when you created the PR. Do you have a world file or blueprint that I can use to reproduce the issue?

**Comment by MatheusMK3** [comment]
Hi @mmusu3, no problems! The people who pointed this to me were from the [Sigma Draconis](https://sigmadraconis.games/) server, which has a save of around 6 months length, which that's why I guess the problem happened, though I got the same issue when trying a pretty much new save I had from my own game too. Basically, trying to run "Replace" seems to trigger a out-of-bounds error on the `TimeSpan` class, so I added a conditional that would catch this error and use the maximum TimeSpan value if it went out-of-bounds.

**Comment by mmusu3** [comment]
Replacing blocks works fine for me on a new world. Do you have any mods on the world you tested with and which blocks did you try to replace? The TimeSpan that is used here is not related to the age of the world so that shouldn't be causing this issue if this is actually where the issue is.

**Comment by MatheusMK3** [comment]
@mmusu3 I had tried in both a brand new world and a save from Sigma Draconis, both containing the same [mods the server uses](https://steamcommunity.com/sharedfiles/filedetails/?id=1838058913). I'm not sure if one of the mods might be causing that or saving invalid data on the save, the code fix on the PR just checks for these edge cases where the value is out-of-bounds for a `TimeSpan` and replaces it with a max-value `TimeSpan`, preventing the program from crashing.

**Comment by mmusu3** [comment]
@MatheusMK3 I have committed a change that attempts to address the problem, however I still cannot reproduce it. I created a new world that contains the block mods from the list that you have provided but I do not know the specific conditions that you used to cause the exception. I would appreciate if you could provide the necessary steps and files to reproduce the issue.
I have not yet published a new release with the committed changes but I have uploaded one here. Please test it out and let me know if it solves the issue. I would still appreciate the files needed to reproduce the issues though, thanks.
[SEToolbox.zip](https://github.com/mmusu3/SEToolbox/files/4999366/SEToolbox.zip)

**Comment by pedrohugorm** [comment]
Hey @MatheusMK3.
I had to implement missing bits of the Interface `IVRageSystem` with Stubs and throws of NotImplementedException().
They were failing the compilation of the code.

**Comment by mmusu3** [comment]
@pedrohugorm Make sure you are using the solution in the Dev folder "./Dev/SEToolbox/SEToolbox.sln". The Main folder is still out of date.

**Comment by mmusu3** [comment]
@MatheusMK3 Did you get a chance to try out the version I posted and did it fix your issue? For now I am going to close this PR.

**Comment by MatheusMK3** [comment]
Hello @mmusu3, sorry for not replying earlier, I have been busy due to some home moving issues and also been away from my personal computer since then. Will take a look on my save files as soon as I can get my desktop up and running.

**Comment by MatheusMK3** [comment]
Just an update, yes it seems to have fixed the issue, at least on the saves I tried it is working correctly now.

**Comment by mmusu3** [comment]
@MatheusMK3 Great, thanks for letting me know. The fixes have since been included in the latest release so you can use that now if you aren't already.

**Pull request closed without merging**
